/**
 * Fill Hotelbeds Mapping Excel Template
 * 
 * Takes the hotel_mapping.csv generated by generateHotelMapping.js
 * and fills the template_confirmation_HBDS.xlsx with the data.
 * 
 * Usage: node scripts/fillMappingExcel.js
 * 
 * Requires: npm install xlsx (already in package.json or install if needed)
 * 
 * Template format (3 columns):
 *   Col A: Client Hotel Code (same as Hotelbeds code since they're our only supplier)
 *   Col B: Hotelbeds Hotel Code
 *   Col C: IsActive (1 = active, 0 = inactive)
 */

const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const TEMPLATE_PATH = path.resolve('C:\\wamp64\\www\\telitrip\\template_confirmation_HBDS.xlsx');
const CSV_PATH = path.join(__dirname, '..', 'hotel_mapping.csv');
const OUTPUT_PATH = path.resolve('C:\\wamp64\\www\\telitrip\\hotel_mapping_FILLED.xlsx');

function main() {
  console.log('=== Fill Hotelbeds Mapping Excel ===\n');

  // Check if CSV exists
  if (!fs.existsSync(CSV_PATH)) {
    console.error('hotel_mapping.csv not found. Run generateHotelMapping.js first.');
    process.exit(1);
  }

  // Read CSV
  const csvContent = fs.readFileSync(CSV_PATH, 'utf8');
  const lines = csvContent.trim().split('\n').slice(1); // skip header
  console.log(`Hotels in CSV: ${lines.length}`);

  // Read template
  const wb = XLSX.readFile(TEMPLATE_PATH);
  const wsName = wb.SheetNames[0];
  const ws = wb.Sheets[wsName];

  // Keep row 1 header intact, start filling from row 2
  // Template columns: A = Client Hotel Code, B = Hotelbeds Hotel Code, C = IsActive
  
  const data = [['Client Hotel Code', 'Hotelbeds Hotel Code', 'IsActive']];
  
  lines.forEach(line => {
    // CSV format: HotelbedsCode,YourHotelCode,"HotelName",CountryCode,DestinationCode,IsActive
    const parts = line.split(',');
    const hotelbedsCode = parts[0]?.trim();
    if (!hotelbedsCode) return;
    
    // Client Hotel Code = same as Hotelbeds code (they're our only supplier)
    // Hotelbeds Hotel Code = the code
    // IsActive = 1
    data.push([hotelbedsCode, hotelbedsCode, 1]);
  });

  // Create new worksheet with data
  const newWs = XLSX.utils.aoa_to_sheet(data);
  wb.Sheets[wsName] = newWs;

  // Write output
  XLSX.writeFile(wb, OUTPUT_PATH);
  console.log(`\n✅ Mapping file generated: ${OUTPUT_PATH}`);
  console.log(`   Total hotels mapped: ${data.length - 1}`);
  console.log(`\nThis file is ready to send to Hotelbeds.`);
}

main();
